#!/usr/bin/env bash
# 20-discover-lab.sh — Phase 3: discover the lab configuration and report exactly
# what is present vs. missing. NEVER prints secret values. Missing external
# dependencies are reported as BLOCKED with a precise "operator must provide"
# list — the automation continues with everything that does NOT depend on them.
set -euo pipefail
# shellcheck source=lib/common.sh
. "$(dirname -- "$0")/lib/common.sh"

RUN_DIR="$(p0_run_dir)"
OUT="$RUN_DIR/lab-discovery.txt"
p0_load_env || true

missing=()
present=()

check_set()  { if [ -n "${!1:-}" ]; then present+=("$1"); else missing+=("$1 — $2"); fi; }
check_file() { # var description  (0400 secret file: existence + mode only)
  local v="$1" d="$2" p="${!1:-}"
  if [ -z "$p" ]; then missing+=("$1 — $d"); return; fi
  if [ ! -f "$p" ]; then missing+=("$1 — path set but file not found ($d)"); return; fi
  local mode; mode="$(stat -c '%a' "$p" 2>/dev/null || echo '?')"
  present+=("$1 (file present, mode $mode)")
}

# Targets / accounts (non-secret identifiers).
check_set  P0_WIN_TARGET   "Windows host with RDP+NLA (host or host:port) — OPERATOR MUST PROVIDE"
check_set  P0_XRDP_TARGET  "Linux xrdp host (host or host:port) — can be auto-provisioned (40-xrdp-target.sh)"
check_set  P0_RDP_PORT     "RDP port (default 3389 if unset)"
check_set  P0_WIN_USER     "Windows test username (e.g. LAB\\\\user) — OPERATOR MUST PROVIDE"
check_set  P0_XRDP_USER    "xrdp test username"

# Credentials (0400 files — never read here).
check_file P0_CRED_VALID_FILE   "valid credential 0400 file — OPERATOR MUST PROVIDE"
check_file P0_CRED_INVALID_FILE "deliberately-wrong credential 0400 file (auth_reject scenario)"

# Certificates / CA (may be auto-generated by 30-make-ca.sh).
check_set  P0_CA_DIR         "controlled CA dir (auto-creatable: 30-make-ca.sh)"
check_set  P0_TRUSTED_CERT   "server cert chained to the controlled CA"
check_set  P0_UNTRUSTED_CERT "unknown/self-signed cert (cert_reject scenario)"

# Egress / allowlist policy (evidence + optional enforcement).
check_set  P0_ALLOWLIST      "worker allowlist addr:port list — derived from targets if unset"

{
  echo "# P0 lab — discovery ($(p0_now_utc))"
  echo "config loaded: ${P0_ENV_LOADED:-0}"
  echo
  echo "## present"
  if [ "${#present[@]}" -gt 0 ]; then printf '  - %s\n' "${present[@]}"; else echo "  (none)"; fi
  echo
  echo "## missing / must be provided"
  if [ "${#missing[@]}" -gt 0 ]; then printf '  - %s\n' "${missing[@]}"; else echo "  (none — lab fully specified)"; fi
  echo
  echo "## credential validation (repo helper; secret never shown)"
  for v in P0_CRED_VALID_FILE P0_CRED_INVALID_FILE; do
    p="${!v:-}"
    if [ -n "$p" ] && [ -f "$p" ]; then
      if tok="$(p0_validate_cred "$p" 2>&1)"; then echo "  $v: $tok"; else echo "  $v: REJECTED ($tok)"; fi
    else
      echo "  $v: not provided"
    fi
  done
} >"$OUT" 2>&1

log "Phase 3 done -> $OUT"
if [ "${#missing[@]}" -gt 0 ]; then
  warn "lab incomplete: ${#missing[@]} item(s) must be provided (see $OUT). Non-dependent phases still run."
fi
# Always succeed: discovery is informational; blocking happens per-scenario.
exit 0
